CREATE DATABASE IF NOT EXISTS u82190 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE u82190;

CREATE TABLE IF NOT EXISTS application (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    biography TEXT,
    login VARCHAR(32) UNIQUE,
    password_hash VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
